export declare const ERROR_CODES: {
    readonly AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS";
    readonly AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED";
    readonly AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID";
    readonly AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED";
    readonly AUTH_FORBIDDEN: "AUTH_FORBIDDEN";
    readonly VALIDATION_FAILED: "VALIDATION_FAILED";
    readonly VALIDATION_INVALID_FORMAT: "VALIDATION_INVALID_FORMAT";
    readonly VALIDATION_MISSING_FIELD: "VALIDATION_MISSING_FIELD";
    readonly RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND";
    readonly RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS";
    readonly RESOURCE_FORBIDDEN: "RESOURCE_FORBIDDEN";
    readonly RESOURCE_CONFLICT: "RESOURCE_CONFLICT";
    readonly QUOTA_EXCEEDED: "QUOTA_EXCEEDED";
    readonly SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED";
    readonly FEATURE_NOT_AVAILABLE: "FEATURE_NOT_AVAILABLE";
    readonly INVALID_OPERATION: "INVALID_OPERATION";
    readonly EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR";
    readonly EXTERNAL_SERVICE_TIMEOUT: "EXTERNAL_SERVICE_TIMEOUT";
    readonly EXTERNAL_SERVICE_UNAVAILABLE: "EXTERNAL_SERVICE_UNAVAILABLE";
    readonly RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED";
    readonly INTERNAL_ERROR: "INTERNAL_ERROR";
    readonly DATABASE_ERROR: "DATABASE_ERROR";
    readonly CACHE_ERROR: "CACHE_ERROR";
};
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
export declare const ERROR_HTTP_STATUS: Record<ErrorCode, number>;
//# sourceMappingURL=error-codes.d.ts.map