/**
 * @er/types - Shared TypeScript Types
 *
 * This package re-exports ALL Prisma-generated types as the single source of truth.
 * Types are generated from apps/api/prisma/schema.prisma
 *
 * Usage:
 *   import type { User, Reminder } from '@er/types';
 */

// Re-export ALL Prisma entity types
export type {
  User,
  UserProfile,
  TrustedContact,
  ApiKey,
  Subscription,
  PaymentHistory,
  Reminder,
  ReminderSchedule,
  ReminderSnooze,
  CompletionCriteria,
  EscalationProfile,
  EscalationState,
  AgentDefinition,
  UserAgentSubscription,
  EmailWatcher,
  WatcherEvent,
  CalendarConnection,
  CalendarSyncRule,
  NotificationLog,
  PendingNotification,
  EventLog,
  AuditTrail,
  AdminUser,
  AdminAction,
  SupportNote,
  SystemHealthSnapshot,
} from '@prisma/client';

// Re-export ALL Prisma enums
export {
  SubscriptionTier,
  SubscriptionStatus,
  ReminderImportance,
  ReminderStatus,
  ScheduleType,
  EscalationStatus,
  EmailProvider,
  CalendarProvider,
  CalendarRuleAction,
  NotificationStatus,
  AdminRole,
} from '@prisma/client';

// Re-export Prisma input types
export type {
  UserCreateInput,
  UserUpdateInput,
  ReminderCreateInput,
  ReminderUpdateInput,
  SubscriptionCreateInput,
  SubscriptionUpdateInput,
  AdminUserCreateInput,
  AdminUserUpdateInput,
  AdminActionCreateInput,
  SupportNoteCreateInput,
  SupportNoteUpdateInput,
  SystemHealthSnapshotCreateInput,
} from '@prisma/client';

// API-specific wrapper types (not generated by Prisma)
export interface ApiResponse<T> {
  success: boolean;
  data: T;
  meta?: {
    timestamp: string;
    requestId: string;
  };
}

export interface PaginatedResult<T> {
  items: T[];
  pagination: {
    page: number;
    pageSize: number;
    totalItems: number;
    totalPages: number;
  };
}

export interface ErrorResponse {
  success: false;
  error: {
    code: string;
    message: string;
    details?: Array<{
      field: string;
      message: string;
    }>;
    requestId: string;
  };
  meta: {
    timestamp: string;
  };
}

// DTOs (thin wrappers around Prisma types)
export interface CreateUserDto {
  email: string;
  password: string;
  displayName: string;
  timezone?: string;
}

export interface LoginDto {
  email: string;
  password: string;
}

export interface TokenPair {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

export interface AccessTokenPayload {
  sub: string; // userId
  email: string;
  tier: SubscriptionTier;
  iat: number;
  exp: number;
}

export interface RefreshTokenPayload {
  sub: string; // userId
  sessionId: string;
  iat: number;
  exp: number;
}

export interface CreateReminderDto {
  title: string;
  description?: string;
  importance: ReminderImportance;
  escalationProfileId: string;
  schedule: CreateScheduleDto;
  completionCriteria?: CreateCompletionCriteriaDto;
}

export interface UpdateReminderDto {
  title?: string;
  description?: string;
  importance?: ReminderImportance;
  escalationProfileId?: string;
}

export interface CreateScheduleDto {
  type: ScheduleType;
  timezone: string;
  triggerAt?: Date;
  cronExpression?: string;
  intervalMinutes?: number;
  excludeDates?: Date[];
  excludeWeekends?: boolean;
}

export interface CreateCompletionCriteriaDto {
  type: 'manual' | 'email_watcher' | 'webhook' | 'api';
  config: Record<string, unknown>;
}

export type CompletionSource = 'manual' | 'email_watcher' | 'webhook' | 'agent' | 'contact';

export interface ReminderFilters {
  status?: ReminderStatus;
  importance?: ReminderImportance;
  page?: number;
  pageSize?: number;
}

// Escalation DTOs
export interface CreateEscalationProfileDto {
  name: string;
  description?: string;
  tiers: EscalationTier[];
}

export interface UpdateEscalationProfileDto {
  name?: string;
  description?: string;
  tiers?: EscalationTier[];
}

export interface EscalationTier {
  tierNumber: number;
  delayMinutes: number;
  agentIds: string[];
  includeTrustedContacts: boolean;
  message?: string;
}

export type EscalationCancelReason = 'acknowledged' | 'completed' | 'snoozed' | 'deleted';

